# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 1
[[main]]
    name = "Schedule"
    url = "/schedule/"
    weight = 2
[[main]]
    name = "Assignments"
    url = "/assignments/"
    weight = 3
[[main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
[[main]]
    name = "<i class='fab fa-slack'></i>"
    url = "https://housingandurb-8ly8093.slack.com"
    weight = 5

