title: Education
baseurl: /
theme: hugo-graphite
googleAnalytics: ''
relativeurls: no
languageCode: en-us
description: Course website for Housing and Urban Policy at University of Illinois at Urbana Champaign.
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - _files$
  - _cache$
preserveTaxonomyNames: yes
permalinks:
  blog: blog/:year/:month/:slug/
taxonomies:
  author: author
  category: categories
  tag: tags
blackfriday:
  angledQuotes: no
  extensions: backslashLineBreak
  hrefTargetBlank: yes
  latexDashes: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: pygments
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
